apiVersion: v1
kind: Namespace
metadata:
  name: ml-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
